<?php
/**
 * @file
 * Install, update, and uninstall functions for the form_reference module.
 */

/**
 * Implements hook_field_schema().
 */
function form_reference_field_schema($field) {
  $columns = array(
    'form_reference' => array('type' => 'varchar', 'length' => 128, 'not null' => FALSE),
  );
  $indexes = array(
    'form_reference' => array('form_reference'),
  );
  return array(
    'columns' => $columns,
    'indexes' => $indexes,
  );
}
