<?php
/**
 * @file
 * Form reference field.
 */

/**
 * Implements hook_field_info().
 *
 * Provides the description of the field.
 */
function form_reference_field_info() {
  return array(
    'form_reference' => array(
      'label' => t('Form reference'),
      'description' => t('Load a referenced form.'),
      'default_widget' => 'options_select',
      'default_formatter' => 'form_reference_form',
      'settings' => array(
        'Content types' => array('content_types' => array()),
        'Core' => array('core' => array()),
        'Auto-discovery' => array('modules' => array()),
        'Module specified' => array('specified' => array()),
        'Manual' => array('custom' => array('custom' => '')),
      ),
    ),
  );
}

/**
 * Implements hook_field_validate().
 *
 * @see form_reference_field_widget_error()
 */
function form_reference_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  foreach ($items as $delta => $item) {
    if (!empty($item['form_reference'])) {
      if (!form_reference_load_includes($item['form_reference'])) {
        $errors[$field['field_name']][$langcode][$delta][] = array(
          'error' => 'invalid_form',
          'message' => t('The form %form could not be found.', array('%form' => $item['form_reference'])),
        );
      }
    }
  }
}


/**
 * Implements hook_field_is_empty().
 *
 * hook_field_is_empty() is where Drupal asks us if this field is empty.
 * Return TRUE if it does not contain data, FALSE if it does. This lets
 * the form API flag an error when required fields are empty.
 */
function form_reference_field_is_empty($item, $field) {
  return empty($item['form_reference']);
}

/**
 * Implements hook_field_settings_form().
 */
function form_reference_field_settings_form($field, $instance, $has_data) {
  // Drupal conventions.
  // Content types.
  $types = array();
  foreach (node_type_get_types() as $type_id => $type) {
    $types['node:' . $type_id] = $type->name;
  }
  $form['Content types'] = array(
    '#type' => 'fieldset',
    '#title' => t('Content types'),
    '#description' => t('Allow content type forms to be referenced.'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['Content types']['content_types'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Content types'),
    '#options' => $types,
    '#default_value' => $field['settings']['Content types']['content_types'],
  );

  // Core forms.
  $core_forms = form_reference_form_options(form_reference_core_forms());

  $form['Core'] = array(
    '#type' => 'fieldset',
    '#title' => t('Core forms'),
    '#description' => t('Core Drupal forms that can be referenced.'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['Core']['core'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Other forms'),
    '#options' => $core_forms,
    '#default_value' => $field['settings']['Core']['core'],
  );

  // Auto-discovery.
  $optional_modules = form_reference_optional_modules();
  $module_links = array();
  foreach ($optional_modules as $module => $module_name) {
    $module_links[] = l($module_name, 'http://www.drupal.org/project/' . $module);
    // Do not present modules as options that aren't enabled.
    if (!module_exists($module)) {
      unset($optional_modules[$module]);
    }
  }
  $form['Auto-discovery'] = array(
    '#type' => 'fieldset',
    '#title' => t('Auto-discovery'),
    '#description' => t('Forms that extend a PHP base class can be auto-discovered:
    <br />') . implode(', ', $module_links),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['Auto-discovery']['modules'] = array(
    '#type' => 'checkboxes',
    '#options' => $optional_modules,
    '#default_value' => $field['settings']['Auto-discovery']['modules'],
  );

  $form['Module specified'] = array(
    '#type' => 'fieldset',
    '#title' => t('Module specified'),
    '#description' => t('Modules that implement hook_form_reference will appear here.'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,

  );
  $form['Module specified']['specified'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Module specified'),
    '#options' => form_reference_form_options(form_reference_form_references()),
    '#default_value' => $field['settings']['Module specified']['specified'],
  );

  // Manual entry.
  $form['Manual'] = array(
    '#type' => 'fieldset',
    '#title' => t('Manual'),
    '#description' => t('Manually specify forms that can be referenced.'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['Manual']['custom']['custom'] = array(
    '#type' => 'textarea',
    '#title' => t('Pre-defined'),
    '#description' => t('Manually enter forms that can be referenced. One per line.'),
    '#default_value' => $field['settings']['Manual']['custom']['custom'],
    '#element_validate' => array('form_reference_validate'),
  );

  return $form;
}

/**
 * Converts passed forms into select options.
 *
 * @param array $forms
 *   Array of forms. @see form_reference_core_forms().
 *
 * @return array
 */
function form_reference_form_options($forms) {
  $form_options = array();

  // Check the forms exist.
  foreach ($forms as $form_id => $form) {
    if (form_reference_load_include($form, $form_id)) {
      $form_options[$form_id] = $form['name'];
    }
  }

  return $form_options;
}

/**
 * @param $form
 *   The form definition.
 * @param $form_id
 *   The form_id.

 * @return bool
 */
function form_reference_load_include($form, $form_id) {
  if (isset($form['file']) && isset($form['module'])) {
    $parts = explode('.', $form['file']);
    $type = array_pop($parts);
    module_load_include($type, $form['module'], implode('.', $parts));
  }
  if (function_exists($form_id)) {
    return TRUE;
  }

  return FALSE;
}

function form_reference_all_forms() {
  $core_forms = form_reference_core_forms();
  $module_forms = form_reference_form_references();

  return array_merge($core_forms, $module_forms);
}

/**
 * Information about core forms.
 *
 * @return array
 */
function form_reference_core_forms() {
  $core_forms = array(
    'user_login' => array(
      'name' => t('User Login'),
    ),
    'user_register_form' => array(
      'name' => t('Create user'),
    ),
    'contact_site_form' => array(
      'name' => t('Contact form'),
      'module' => 'contact',
      'file' => 'contact.pages.inc',
    ),
    'search_form' => array(
      'name' => t('Search form'),
    ),
  );

  return $core_forms;
}

/**
 * Validation function for manually entered forms.
 *
 * @param $element
 * @param $form_state
 */
function form_reference_validate($element, &$form_state) {
  $value = $element['#value'];
  if (!empty($value)) {
    // Check manually entered forms exist.
    $custom_forms = explode("\r\n", $value);
    $messages = array();
    $valid = TRUE;
    foreach ($custom_forms as $form) {
      // This won't work for class based forms but these should be auto-discovered.
      if (!function_exists($form)) {
        $valid = FALSE;
        $messages[] = t("The form %form could not be found.", array('%form' => $form));
      }
    }
    if (!$valid) {
      form_error($element, check_plain(implode('<br />', $messages)));
    }
  }
}

/**
 * Implements hook_field_formatter_info().
 */
function form_reference_field_formatter_info() {
  return array(
    'form_reference_form' => array(
      'label' => t('Render form'),
      'field types' => array('form_reference'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function form_reference_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'form_reference_form':
      foreach ($items as $delta => $item) {
        form_reference_load_includes($item['form_reference']);
        if (strpos($item['form_reference'], 'node:') !== FALSE) {
          module_load_include('inc', 'node', 'node.pages');
          $content_type = str_replace('node:', '', $item['form_reference']);
          $element[$delta] = node_add($content_type);
        }
        else {
          $element[$delta] = drupal_get_form($item['form_reference']);
        }
      }
      break;
  }

  return $element;
}

/**
 * Loads include files for a form.
 *
 * @param $form_id
 *
 * @return bool
 */
function form_reference_load_includes($form_id) {
  $forms = form_reference_all_forms();

  if (isset($forms[$form_id])) {
    return form_reference_load_include($forms[$form_id], $form_id);
  }
  else {
    // If it's an auto-discovered form we don't need to load includes.
    // Check that we can load the form.
    $optional_modules = form_reference_optional_modules('validation_element');
    foreach ($optional_modules as $validation_element) {
      $loaded_form = drupal_get_form($form_id);
      if (isset($loaded_form[$validation_element])) {
        return TRUE;
      }
    }
    return FALSE;
  }
}

/**
 * Implements hook_field_widget_info_alter().
 */
function form_reference_field_widget_info_alter(&$info) {
  if (module_exists('options')) {
    $info['options_select']['field types'][] = 'form_reference';
  }
}

/**
 * Implements hook_field_widget_error().
 *
 * hook_field_widget_error() lets us figure out what to do with errors
 * we might have generated in hook_field_validate(). Generally, we'll just
 * call form_error().
 *
 * @see form_reference_field_validate()
 * @see form_error()
 */
function form_reference_field_widget_error($element, $error, $form, &$form_state) {
  switch ($error['error']) {
    case 'form_reference_invalid':
      form_error($element, $error['message']);
      break;
  }
}

/**
 * Implements hook_options_list().
 */
function form_reference_options_list($field, $instance = NULL, $entity_type = NULL, $entity = NULL) {
  // Content types.
  $settings = $field['settings'];
  $form_options = array();
  foreach ($settings as $category_key => $category) {
    if (is_array($category) && !empty($category)) {
      if (!in_array($category_key, array('Auto-discovery', 'Manual', 'Custom'))) {
        foreach ($category as $category_name => $category_forms) {
          foreach ($category_forms as $form => $value) {
            if (!$value) {
              unset($category[$category_name][$form]);
            }
          }
        }
        reset($category);
        if (key($category)) {
          $form_options[drupal_ucfirst($category_key)] = $category[key($category)];
        }
      }
    }
  }

  // Auto-discovery of optional modules.
  $optional_modules = form_reference_optional_modules('namespace');
  foreach ($settings['Auto-discovery']['modules'] as $parent_class) {
    if ($parent_class) {
      foreach (get_declared_classes() as $class) {
        if (is_subclass_of($class, $optional_modules[$parent_class])) {
          $form_options['Auto-discovery'][$class::getFormId()] = $class::getFormId();
        }
      }
    }
  }
  unset($form_options['auto_discovery']['modules']);

  // Custom forms.
  $custom_forms = explode("\r\n", $settings['Manual']['custom']['custom']);
  foreach ($custom_forms as $form) {
    if ($form) {
      $form_options['Custom'][$form] = $form;
    }
  }

  return $form_options;
}

/**
 * Returns optional modules for auto-discovery.
 *
 * $return_value
 *  What element to return.
 *
 * @return string
 *  The element value.
 */
function form_reference_optional_modules($return_value = 'name') {
  $optional_modules = array(
    'cool' => array(
      'namespace' => 'Drupal\cool\BaseForm',
      'name' => 'Cool',
      'validation_element' => 'cool_class_name', // Existence of this element is checked in validation.
    ),
    /* Unfortunately ghost classes don't seem to be discoverable.
    'ghost' => array(
      'namespace' => 'Drupal\ghost\Form\BaseForm',
      'name' => 'Ghost',
    ),
    */
  );
  $return = array();
  foreach ($optional_modules as $module_key => $module) {
    $return[$module_key] = $module[$return_value];
  }

  return $return;
}

/**
 * Implements hook_form_reference().
 *
 * $forms = array(
 *  'contact_site_form' => array(
 *    'name' => t('Contact form'),
 *    'module' => 'contact',
 *    'file' => 'contact.pages.inc',
 *  ),
 *  'my_form_id' => array(
 *    'name' => t('Name appears in select options'),
 *    'module' => 'the_module_the_form_is_in', // Optional.
 *    'file' => 'file_that_form_is_in.inc', // Optional.
 *  );
 */
function form_reference_form_reference() {
  $forms = array(
    'user_login' => array(
      'name' => t('User Login'),
    ),
  );

  return $forms;
}

/**
 * Loads forms from other modules implementing hook_form_reference().
 */
function form_reference_form_references() {
  $forms = array();
  foreach (module_implements('form_reference') as $module) {
    $module_forms = module_invoke($module, 'form_reference');
    $forms = array_merge($forms, $module_forms);
  }

  return $forms;
}